using UnityEngine;
using UnityEngine.UI;

namespace SnakeSnack.UI
{
    /// <summary>
    /// Builds the interface bricks (a <c>Text</c>, an <c>Image</c>) with the settings every screen of
    /// the game must share.
    /// </summary>
    /// <remarks>
    /// ⚠ <b>The whole interface is built in code</b>, never assembled in the scene: a serialised
    /// reference to a renamed <c>Text</c> comes back null <b>in the regenerated scene</b>
    /// (<c>SceneBuilder</c>), and the only symptom is text that does not appear. This factory exists
    /// so screens can resemble each other without copying each other: the day overflow or raycasting
    /// changes, it changes in one place.
    /// </remarks>
    public static class UiFactory
    {
        /// <summary>A text placed by anchor, position and size, in pixels of the 1280x720 frame.</summary>
        /// <remarks>
        /// ⚠ <b>Never <c>FontStyle.Bold</c></b>: weight comes from the FILE (SemiBold or ExtraBold).
        /// uGUI's synthetic bold would add itself to an already bold drawing and clog Nunito's round
        /// counters — exactly what ART §2.4 forbids.
        /// </remarks>
        public static Text Text(
            Transform parent, string name, Font font, int size, TextAnchor alignment,
            Color colour, Vector2 anchor, Vector2 position, Vector2 size2d)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);

            var text = go.AddComponent<UnityEngine.UI.Text>();
            text.font = font;
            text.fontStyle = FontStyle.Normal;
            text.fontSize = size;
            text.alignment = alignment;
            text.color = colour;
            text.raycastTarget = false;
            text.horizontalOverflow = HorizontalWrapMode.Overflow;
            text.verticalOverflow = VerticalWrapMode.Overflow;

            Place(go.GetComponent<RectTransform>(), anchor, position, size2d);
            return text;
        }

        /// <summary>A solid rectangle, placed the same way as a text.</summary>
        public static Image Rectangle(
            Transform parent, string name, Color colour, Vector2 anchor, Vector2 position, Vector2 size)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);

            var image = go.AddComponent<Image>();
            image.color = colour;
            image.raycastTarget = false;

            Place(go.GetComponent<RectTransform>(), anchor, position, size);
            return image;
        }

        /// <summary>An image stretched over its whole parent (scrim, backdrop).</summary>
        public static Image Scrim(Transform parent, string name, Color colour)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);

            var image = go.AddComponent<Image>();
            image.color = colour;
            image.raycastTarget = false;

            var rect = go.GetComponent<RectTransform>();
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;
            return image;
        }

        /// <summary>
        /// An overlay canvas, at the given sorting order.
        /// </summary>
        /// <remarks>
        /// ⚠ <b>Sorting order is the only arbiter</b> (<c>docs/pitfalls/interface.md</c>): two
        /// canvases at the same order stack by hierarchy, which is not stable when the scene is
        /// regenerated by code. Every canvas in the game sets one explicitly — build stamp 1000, menu
        /// 200, HUD 100.
        /// </remarks>
        public static Canvas Canvas(Transform parent, string name, int order)
        {
            var go = new GameObject(name);
            go.transform.SetParent(parent, false);

            var canvas = go.AddComponent<UnityEngine.Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = order;

            var scaler = go.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1280f, 720f);

            go.AddComponent<GraphicRaycaster>();
            return canvas;
        }

        private static void Place(RectTransform rect, Vector2 anchor, Vector2 position, Vector2 size)
        {
            rect.anchorMin = anchor;
            rect.anchorMax = anchor;
            rect.pivot = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = position;
            rect.sizeDelta = size;
        }
    }
}
